apiVersion: v1
kind: Pod
metadata:
  labels:
    app: init-container
  name: init-container
spec:
  initContainers:
    - name: clone-repo
      image: alpine/git
      command:
        - git
        - clone
        - --progress
        - https://github.com/danielcifuentes54/kubernetes-patterns.git
        - /tmp && cp /tmp/kubernetes-patterns/01-init-containers/index.html usr/share/nginx/html 
      volumeMounts:
        - name: web
          mountPath: '/usr/share/nginx/html'
  containers:
    - name: nginx
      image: nginx
      ports:
        - name: http
          containerPort: 80
      volumeMounts:
        - name: web
          mountPath: '/usr/share/nginx/html'
  volumes:
    - name: web
      emptyDir: {}

--- 

apiVersion: v1
kind: Service
metadata:
  name: init-container-service
spec:
  ports:
  - name: 80-80
    nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: init-container
  type: NodePort