apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  default.conf: |
    server {
      listen       80;
      server_name  localhost;
      location / {
          root   /usr/share/nginx/html;
          index  index.html index.htm;
      }
      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /usr/share/nginx/html;
      }
      location /nginx_status {
        stub_status;
        ##commented for testing purpose
        #allow 127.0.0.1;  #only allow requests from localhost 
        #deny all;   #deny all other hosts 
      }
    }

---

apiVersion: v1
kind: Pod
metadata: 
  name: webserver
  labels:
    app: adapter
spec:
  containers:
  - name: webserver
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /etc/nginx/conf.d
      name: nginx-conf
      readOnly: true
  - name: adapter
    image: nginx/nginx-prometheus-exporter:0.4.2
    args: ["-nginx.scrape-uri","http://localhost/nginx_status"]
    ports:
    - containerPort: 9113
  volumes:
  - name: nginx-conf
    configMap:
      name: nginx-conf
      items:
      - key: default.conf
        path: default.conf

---

apiVersion: v1
kind: Service
metadata:
  name: adapter-service
spec:
  ports:
  - name: nginx
    nodePort: 30002
    port: 80
    protocol: TCP
    targetPort: 80
  - name: adapter
    nodePort: 30003
    port: 9113
    protocol: TCP
    targetPort: 9113
  selector:
    app: adapter
  type: NodePort

# custom Nginx metrics --> curl localhost:30002/nginx_status
# Prometheus metrics --> curl localhost:30003/metrics